### ISSUE TITLE
Shared folders support

### ISSUE THREAD

**Issue by kyazdani42** [timanovsky/subdir-heroku-buildpack#7]
Hi,
our current directory structure looks like
web/...
api/...
sdk/...
where api and web load code from sdk. The issue i have is that when trying to load the sdk from the web or the api projects, it just breaks because sdk is removed.
I thought maybe there already was a configuration option, but i looks like this buildpack just removes everything.
Do you have an existing solution or could i try to implement a feature to keep some paths in the directory ? It would be greatly appreciated :)
Thanks for this buildpack anyway, solved many of my issues.

**Comment by GMolini** [comment]
hi @kyazdani42 , i have this exact problem. How did you solve this? My problem is that the build fails because the files that are outside the current directory are not dound

**Comment by kyazdani42** [comment]
Hi, i do not remember perfectly how i did this, but what i remember is forking the buildpack and modifying it to copy the necessary files to the repository in a dedicated folder.

**Comment by GMolini** [comment]
Jeje thanks, i just figured it out and have done exacly that. thanks for replying anyway

**Comment by GMolini** [comment]
Just in case anybody needs it, the modified buildpack can be found here: https://github.com/GMolini/heroku-buildpack-subdir-to-root-extra-dirs
